version: '3.8'

services:
  streamlit_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./data:/app/data
      - ./.streamlit:/app/.streamlit
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend_app:8000
    depends_on:
      - backend_app

  backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1  
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - ENABLE_LOCAL_LLM=false