version: '3.8'

services:
  streamlit_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1